GET http://localhost:3333/academicWork/
Content-Type: application/json

{

}
###

POST http://localhost:3333/user/register
Content-Type: application/json

{
    "name": "Natan Silva",
    "email": "tansinho@gmail.com",
    "registrationNumber": "2020",
    "role": "LIBRARIAN",
    "password": "12345",
    "confirmPassword": "12345"
}

###
POST http://localhost:3333/user/login
Content-Type: application/json

{
    "registrationNumber": "2020",
    "password": "12345",
    "asdf": "12345"
}
###

POST  http://localhost:3333/librarian/reset-password-request
Content-Type: application/json

{
    "id": "e47ebba4-f3b7-4bab-821c-edac97a24a04"
}

###
POST  http://localhost:3333/librarian/reset-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU0N2ViYmE0LWYzYjctNGJhYi04MjFjLWVkYWM5N2EyNGEwNCIsImlhdCI6MTc1Njc3OTgxNCwiZXhwIjoxNzU2ODA4NjE0fQ.9Rd3M7lyRu_qLqX0itTDg5OezfeCPUvWuZ84a_15GS4
Content-Type: application/json

{
    "id": "e47ebba4-f3b7-4bab-821c-edac97a24a04",
    "newPassword": "2asdfkljasdklfjasklfjsdkljfkasdjfiejklasdjklfjasdiofjasdiofjioejioasdjfioasdjfioejklasdjfaiosdjf",
    "confirmPassword": "2asdfkljasdklfjasklfjsdkljfkasdjfiejklasdjklfjasdiofjasdiofjioejioasdjfioasdjfioejklasdjfaiosdjf"
}

###
POST http://localhost:3333/librarian/register
Content-Type: application/json

{
    "name": "Pedro Lucas",
    "email": "pedrinho@luca.com",
    "registrationNumber": "558646846",
    "password": "admin",
    "confirmPassword": "admin"
}

###
GET  http://localhost:3333/librarian/list
Authorization: Bearer .eyJpZCI6ImEwMTU0ZmM2LTlhNjQtNDA0YS1hMDZkLWJhOWY3YWZkMzU1ZiIsImlhdCI6MTczMTk0ODk5NywiZXhwIjoxNzMxOTc3Nzk3fQ.BuClEIsdWc5bA7RQC7bGYzIp81gjJE7ROvN9wXLcd18


###
POST  http://localhost:3333/advisor/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2M2FhN2U4LWZmZDctNGMwOS04M2FmLWU1ZTdjOTdlYTdhZSIsImlhdCI6MTc1NzQ3MTIwNywiZXhwIjoxNzU3NDc4NDA3fQ.C6V6JAz4lh01y7wodrLCzHV3BTM8TWwjt6C9-eq1dBs
Content-Type: application/json

{
    "name": "Ferando",
    "surname": "asdf",
    "registrationNumber": "1"
}

###
PUT  http://localhost:3333/advisor/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2M2FhN2U4LWZmZDctNGMwOS04M2FmLWU1ZTdjOTdlYTdhZSIsImlhdCI6MTc1NzQ3MTIwNywiZXhwIjoxNzU3NDc4NDA3fQ.C6V6JAz4lh01y7wodrLCzHV3BTM8TWwjt6C9-eq1dBs
Content-Type: application/json

{
   "advisorIdentification": "0d51f335-60f9-4583-bbb8-563888717e58",
   "updateFields": {
        "name": "Raquel-adicional-EDITADA",
        "surname": "Cesar Pereira"
   }
}

###
DELETE  http://localhost:3333/advisor/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2M2FhN2U4LWZmZDctNGMwOS04M2FmLWU1ZTdjOTdlYTdhZSIsImlhdCI6MTc1NzQ3MTIwNywiZXhwIjoxNzU3NDc4NDA3fQ.C6V6JAz4lh01y7wodrLCzHV3BTM8TWwjt6C9-eq1dBs
Content-Type: application/json

{
   "advisorIdentification": "cb8b3a3e-c2cd-4144-be1c-64b9647b50d9"
}

###
GET  http://localhost:3333/advisor/list
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVlZjYwZWNjLTY2YTktNDhhMy1hMzgwLTJjOWE4YTZlMTQxNSIsImlhdCI6MTc1NzI2MjEyMCwiZXhwIjoxNzU3MjY1NzIwfQ.14RP2Ce_eF_MmJ2WtovvFlJRg_6oGja8Y1OiHydnHTc


###
GET  http://localhost:3333/course/list

###
POST  http://localhost:3333/course/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdmOThkMjIyLTBlMzgtNDY5NS04OTI2LTIzMmNiMmIyOGUyZSIsImlhdCI6MTc1NzI5NzkxMywiZXhwIjoxNzU3MzAxNTEzfQ.3sk0hFTbSJ2aDj1uDGs7s4ASkGx3EHAt408mGAVN_e4

{
    "name": "Sistemas de Informação",
    "courseCode": "CO1231025",
    "degreeType": "BACHELOR"
}


###
PUT  http://localhost:3333/course/update
Content-Type: application/json

{
    "courseId": "e550b557-9709-48ba-8c33-e1616052ceb5",
    "updateFields": {
        "name": "Engenharia da Computaria",
        "courseCode": "ENG005"
    }
}

###
DELETE  http://localhost:3333/course/delete
Content-Type: application/json

{
    "courseId": "17e2d58c-ddb7-4d09-a7b9-82896ed52344"
}

# TESTE PARA ACADEMIC WORK

###

POST http://localhost:3333/academicWork/changeVisibility
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2M2FhN2U4LWZmZDctNGMwOS04M2FmLWU1ZTdjOTdlYTdhZSIsImlhdCI6MTc1NzQ3MzcyNSwiZXhwIjoxNzU3NDgwOTI1fQ.CaI3mDqcVu-KMkDcXZ3phYocItuxvO0UwQegLEKaPL8
Content-Type: application/json

{
    "id": "ed4c73d3-fd08-477a-8435-54f8ce973000"
}
###
POST  http://localhost:3333/course/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVhMzI4MjI4LTFlYTMtNGU2MS04YmQ0LTJiOWJhYWIzMjA3NSIsImlhdCI6MTc1NzI5NjczNiwiZXhwIjoxNzU3MzAwMzM2fQ.vAgUfKnkbMcrFDmMuTNzmbsslBmpNooeuFfXMGt0Il4
{
    "name": "Sistemas de Informação",
    "courseCode": "CO1025",
    "degreeType": "BACHELOR"
}

###

DELETE  http://localhost:3333/academicWork/ed4c73d3-fd08-477a-8435-54f8ce973000/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2M2FhN2U4LWZmZDctNGMwOS04M2FmLWU1ZTdjOTdlYTdhZSIsImlhdCI6MTc1NzQ3MzcyNSwiZXhwIjoxNzU3NDgwOTI1fQ.CaI3mDqcVu-KMkDcXZ3phYocItuxvO0UwQegLEKaPL8
Content-Type: application/json

{
    
}


###

POST http://localhost:3333/academicWork/addAdvisor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2M2FhN2U4LWZmZDctNGMwOS04M2FmLWU1ZTdjOTdlYTdhZSIsImlhdCI6MTc1NzQ3MzcyNSwiZXhwIjoxNzU3NDgwOTI1fQ.CaI3mDqcVu-KMkDcXZ3phYocItuxvO0UwQegLEKaPL8
Content-Type: application/json

{
    "academicWorkId": "f2f05936-e960-4506-8144-ff3a72137e73",
    "advisorId": "ac9dac50-d9e8-423f-b69c-a5ee577823b7"
}

###

DELETE http://localhost:3333/academicWork/deleteAdvisor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2M2FhN2U4LWZmZDctNGMwOS04M2FmLWU1ZTdjOTdlYTdhZSIsImlhdCI6MTc1NzQ3MzcyNSwiZXhwIjoxNzU3NDgwOTI1fQ.CaI3mDqcVu-KMkDcXZ3phYocItuxvO0UwQegLEKaPL8
Content-Type: application/json

{
    "academicWorkId": "f2f05936-e960-4506-8144-ff3a72137e73",
    "advisorId": "ac9dac50-d9e8-423f-b69c-a5ee577823b7"
}