version: "3"

services:
  postgress:
    container_name: postgress_container_repoIFF
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    # volumes:
    #   - ./db-postgres/:/var/lib/postgresql/data/.:rw
    # network_mode: host
    ports:
      - "5432:5432"
    tty: true

# volumes:
#   db-postgres:
