version: "3"

services:
  # app-backend-dev:
  #   image: node:20-alpine
  #   container_name: repoIFF_backend-dev
  #   ports:
  #     - "3333:3333"
  #   env_file:
  #     - ./repositiff-backEnd/.env
  #   working_dir: /app
  #   volumes:
  #     - ./prisma:/app/prisma
  #     - ./src:/app/src
  #     - ./node_modules:/app/
  #   depends_on:
  #     - postgress
  #   command: npm run dev

  postgress:
    container_name: postgress_container_repoIFF
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    # volumes:
    #   - ./db-postgres/:/var/lib/postgresql/data/.:rw
    # network_mode: host
    ports:
      - "5432:5432"
    tty: true
# volumes:
#   db-postgres:
